### ISSUE TITLE
Move minpack under fortran-lang

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm-registry#45]
A candidate repository to move could be this one:

https://github.com/certik/minpack

**Comment by zoziha** [comment]
`minpack` helped me a lot in solving nonlinear equations.

Will `minpack` also be transferred to the fortran-lang organization for maintenance?
I saw that @jacobwilliams updated [a modernized `minpack`](https://github.com/jacobwilliams/minpack). If the fortran-lang organization intends to maintain `minpack`, maybe we can focus on a same repository, such as: https://github.com/certik/minpack .

**Comment by awvwgk** [comment]
I don't see an issue with maintaining it under Fortran-lang if there are enough contributors interested in it. We can use this issue to plan this project, @certik can than transfer the project once we agreed here.

**Comment by certik** [comment]
@jacobwilliams what kind of changes did you do in your modern Fortran minpack? I was looking at the main file:

* https://github.com/jacobwilliams/minpack/blob/b4e671d1692b6f9eb048ba920e97f8a4eda195e3/src/minpack.f90

And that looks pretty good to me. No derived types. :) Unlike with fftpack, I don't have much experience with performance of minpack or how critical it is. It seems the utility there is for the functionality itself?

So we might want to start with your version at https://github.com/jacobwilliams/minpack/ instead of the version that @zoziha, @brocolis and I were maintaining at https://github.com/certik/minpack, assuming we all like the changes that you did.

**Comment by jacobwilliams** [comment]
I didn't realize you were maintaining a version. What i am currently doing is modernizing the coding style, documentation, unit tests, etc. to get it up to current standards as it currently exists. Then will look into improving the algorithms or adding new ones. I don't promise not to add classes though! :)

**Comment by certik** [comment]
Well, it seems if we add new algorithms or improve the algorithms besides obvious bug fixes, it should be called differently, what do you think? We can still maintain `minpack` (in the original form, but modernized) and the new library under fortran-lang as two separate repositories.

**Comment by jacobwilliams** [comment]
Well maybe...or maybe not. I don't like to encourage Fortranners to think that libraries are frozen and will never change. That's part of the reason we are in the mess we are in now. :) Minpack could have been continuously updated over these past 40 years and kept up to date with the last language standards and the latest algorithms, etc instead of being frozen in amber. So I prefer to think we are restarting Minpack development where it left off.

I could use tags and releases to indicate the old version? Say `1.0` is the original "pile of FORTRAN 77 routines", `1.1` is the slightly modernized module version that is functionally equivalent, and then go from there. That's one way to do it.

**Comment by certik** [comment]
Good point. Why don't you join us for the Fortran call tomorrow and we can discuss this.

**Comment by zoziha** [comment]
Should we now register [the `minpack` under the fortran-lang namespace](https://github.com/fortran-lang/minpack) to the fpm-registry?

Or should we wait for `minpack` to be marked with a pre-release/release tag?

**Comment by milancurcic** [comment]
@zoziha I think so.

**Comment by awvwgk** [comment]
This is resolved.
